name: Build and Publish

on:
  push:
    tags:
      - v*
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - uses: actions/setup-node@v4

      - run: npm ci
        working-directory: ./GdsBlazorComponents

      - run: npm run build
        working-directory: ./GdsBlazorComponents

      - run: dotnet restore

      - run: dotnet build --configuration Release --no-restore

      - run: dotnet pack --configuration Release --no-build

      - uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: '**/*.nupkg'

  publish:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # enable GitHub OIDC token issuance for this job

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - uses: actions/download-artifact@v4
        with:
          name: nuget-package

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{secrets.NUGET_USER}} # Recommended: use a secret like ${{ secrets.NUGET_USER }} for your nuget.org username (profile name), NOT your email address
    
      - run: dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{steps.login.outputs.NUGET_API_KEY}} --skip-duplicate --no-symbols
